server:
  port: 8080

spring:
  profiles:
    active: db
  datasource:
    url: jdbc:postgresql://ep-fancy-salad-b6tlytcv-pooler.c-2.sa-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_By1vGphSFq2W

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
